### PR TITLE
Part03StepVerifier. "notice how long" parts added

### PR DESCRIPTION
**Pull request by senleft**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@senleft Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/lite-rx-api-hands-on&pullRequestId=69)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/lite-rx-api-hands-on&pullRequestId=69) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@senleft Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/lite-rx-api-hands-on&pullRequestId=69)!

**Comment by simonbasle** [comment]
Thanks for attempting to improve the workshop. I don't think the main class nor the `solution` branch are proper: the assertion should rather go in the `Part03StepVerifierTest`, in the `master` branch. You can either open a new PR or try to rework that one (do some local rebasing if needed then `Edit` title of PR to change the base branch)

**Review by simonbasle — CHANGES_REQUESTED** [review]
Thanks for attempting to improve the workshop. I don't think the main class nor the `solution` branch are proper: the assertion should rather go in the `Part03StepVerifierTest`, in the `master` branch. You can either open a new PR or try to rework that one (do some local rebasing if needed then `Edit` title of PR to change the base branch)

**Comment by simonbasle** [comment]
closing due to inactivity

**Pull request closed without merging**
