### PR TITLE
Align Flux and Mono error handling APIs

### PR DESCRIPTION
**Pull request by SystemOutPrint**

### CODE REVIEW

**Comment by SystemOutPrint** [comment]
The api used in 《Developing Reactive applications with Reactive Streams and Java8》has been renamed.

**Comment by SystemOutPrint** [comment]
Sry, I don't understand your reply~

**Comment by simonbasle** [comment]
@SystemOutPrint your PR doesn't make much sense as it modifies a branch where the exercices are empty and just adds a comment. Where exactly did you spot the old API?

**Comment by SystemOutPrint** [comment]
https://www.youtube.com/watch?v=Cj4foJzPF80

**Comment by SystemOutPrint** [comment]
ok~ O(∩_∩)O

**Comment by simonbasle** [comment]
@SystemOutPrint ah I see, but that's a recording from 2016... Yes the API have evolved since then, and the workshop codebase has followed 👍

**Pull request closed without merging**
