### PR TITLE
Use Flux.just() instead of Mono.just()

### PR DESCRIPTION
**Pull request by martin-flower**
Hi Sébastien, suggest use Flux instead of Mono in solution to betterCallSaulForBogusFlux() - better aligned with method signature and comments.

### CODE REVIEW

**Comment by sdeleuze** [comment]
Hey Martin thanks for your feedback, I see your point. Could you just modify your commit and the test to return 2 users instead of 1? That will make `Flux` usage more meaningful.

**Comment by martin-flower** [comment]
Hi Stéphane - is this what you had in mind?

**Comment by sdeleuze** [comment]
My name is Sébastien, but yes that's what I had in mind ^^

**Comment by martin-flower** [comment]
Whoops - apologies. (Got it right earlier on mind you : ) )

**Pull request merged**
